### ISSUE TITLE
Trouble using theme

### ISSUE THREAD

**Issue by SwedishGojira** [diomed/casper#1]
I'm sorry to say I can not activate this theme in a fresh install.

I have installed it via both the admin area and tried uploading it manually.
The theme does not show up in the theme area of the admin menu, even though it is shown as active theme when I browse the themes available to install.
![1](https://user-images.githubusercontent.com/1439531/47208644-a57c3e80-d38e-11e8-944f-670669f42193.png)
![2](https://user-images.githubusercontent.com/1439531/47208646-a614d500-d38e-11e8-8586-3efcf609b496.png)

Also when  I go to "Configuration - System" only "Quark" show up under default theme, even though I have manually edited system.yaml.
![3](https://user-images.githubusercontent.com/1439531/47208647-a614d500-d38e-11e8-8b02-2cbc5bfad717.png)
![4](https://user-images.githubusercontent.com/1439531/47208648-a614d500-d38e-11e8-9d95-cb122acd8252.png)

I am using the 1.6 beta 3 version, but I get the same problem with the 1.5 version also.
No problem activating other themes at all.

**Comment by diomed** [comment]
please go to user/themes/casper2
and rename it to **casper**


[yes, via FTP] :(
then let me know is it good or not.

**Comment by diomed** [comment]
I've asked for change of repo name on GPM, so this should be fixed soon. 
sorry for inconvenience, and thanks for trying the theme, and reporting the bug.

**Comment by sebasvisser** [comment]
Changing the name of the folder to casper seems to fix this yeah
