### ISSUE TITLE
Hard coding "blog" is too limiting

### ISSUE THREAD

**Issue by ganar** [diomed/casper#12]
I like Casper, but the current way of implementing the collections in [the blog template](https://github.com/diomed/casper/blob/master/templates/blog.html.twig) is too limiting and prone to error.

````
{% for post in page.find('/blog').collection.order('publish_date', 'desc') %}
````

I suggest that the template grabs the collection from the YAML header, or at least the children of the current page

**Comment by diomed** [comment]
I like Casper too but this project is in limbo.
You could send PR if you want to, and I'll hopefully merge, but main point is  - you'll have to fix it yourself 
or ask someone else on grav community to help you out. I'm simply not developing anymore.
I'm sorry.

**Comment by ganar** [comment]
Thanks for the update, @diomed .

There are some files missing that I would need —scss folder—  I can certainly do corrections in the code.
