### ISSUE TITLE
Post images break if they have a space in their name

### ISSUE THREAD

**Issue by xy3** [diomed/casper#16]
If primary images are uploaded and have spaces in their name e.g., 'big image.jpg' instead of 'big-image.jpg', the CSS `background-image` property breaks.

Example:
![Example issue](https://i.imgur.com/jGSUaKm.png)

And it looks like:
![Post](https://i.imgur.com/jHQzz5K.png)

It's a pretty straightforward fix I think. Twig has an `escape('css')` filter that should do the trick.

**Comment by diomed** [comment]
Fixed by you. YAY! 👍
