### ISSUE TITLE
Image Item are not displayed on the smartphone

### ISSUE THREAD

**Issue by raffifu** [diomed/casper#9]
![raffifu xyz_ iphone x 1](https://user-images.githubusercontent.com/22138274/50537978-62162b80-0b9a-11e9-8ecd-5cde5e2c069b.png)

**Comment by raffifu** [comment]
![ss1](https://user-images.githubusercontent.com/22138274/50537989-b15c5c00-0b9a-11e9-9703-a405163a068a.png)

image preview in dekstop browser

**Comment by raffifu** [comment]
i have fix it

**Comment by diomed** [comment]
@raffifu care to share how you fixed it and what was wrong? 
so I can apply fix for everyone.

I was somewhat busy these days and couldn't take a look.

**Comment by raffifu** [comment]
i found it
![50549148-1b076380-0c8a-11e9-9cd0-32b8db0dd15c](https://user-images.githubusercontent.com/22138274/50549219-c1079d80-0c8b-11e9-9290-31638f82befa.png)
then i delete it
![screen](https://user-images.githubusercontent.com/22138274/50549231-e399b680-0c8b-11e9-94d9-42260fd4473e.png)

**Comment by diomed** [comment]
ok. thank you
